AWSTemplateFormatVersion: 2010-09-09

Description: >
  Deploys Laravel on ECS Fargate using an existing ECS Cluster and Service Discovery Namespace

Parameters:
  pVpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the Virtual Private Network (VPC)
  pSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the ECS tasks
  pClusterStackName:
    Type: String
    Description: Name of the cluster stack exporting the required values
    Default: gusi-cluster
  pAlbStackName:
    Type: String
    Description: The name of the ALB stack.
    Default: cluster-alb-gusi
  pDesiredCount:
    Type: Number
    Description: Desired amount of tasks to run on the ECS service.
    Default: 1
  pImageVersion:
    Type: String
    Description: The version tag of the container image.
    Default: latest

Resources:

  # Security Group
  serviceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow all traffic from self and ALB Security Group
        VpcId: !Ref pVpcId

  # Allow everything that has this security group attached
  serviceSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt serviceSecurityGroup.GroupId
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !GetAtt serviceSecurityGroup.GroupId

  serviceVpcIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt serviceSecurityGroup.GroupId
      IpProtocol: -1  # Allows all protocols
      FromPort: -1    # Allows all ports
      ToPort: -1      # Allows all ports
      CidrIp: 10.2.0.0/16

  # ECS Service for Laravel
  laravelService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue 
        Fn::Sub: ${pClusterStackName}:FargateClusterArn
      ServiceName: laravel-service
      DeploymentController:
        Type: CODE_DEPLOY
      TaskDefinition: !Ref pTaskDefinitionArn
      LoadBalancers:
        - ContainerName: laravel-container
          ContainerPort: 80
          TargetGroupArn: !Join 
            - ''
            - - !ImportValue 
                Fn::Sub: laravel-blue-tg-${pAlbStackName}
      DesiredCount: !Ref pDesiredCount
      EnableExecuteCommand: true
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref pSubnetIds
          SecurityGroups:
            - !GetAtt serviceSecurityGroup.GroupId
          AssignPublicIp: DISABLED
      ServiceRegistries:
        - RegistryArn: !ImportValue 
            Fn::Sub: ${pClusterStackName}:ServiceDiscoveryServiceArn

Outputs:
  EcsImageVersion:
    Description: ECS Image Version
    Value: !Ref pImageVersion
    Export:
      Name: !Sub ${AWS::StackName}:EcsImageVersion

  ECSServiceName:
    Description: Service Name
    Value: !Ref laravelService