AWSTemplateFormatVersion: 2010-09-09
Description: Creates an ECR repo with 8 image retention policy
Parameters:
  pEcrRepoName:
    Type: String
    Description: >-
      ECR Repo name

Resources:
  ecrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${pEcrRepoName}
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 8 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 8
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ecrRepo.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}:ECRRepoURI