version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  # After the "Install" lifecycle hook,
  # which is the hook that copies all the contents declared in the 'files' section above
  AfterInstall: 
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  
  
