AWSTemplateFormatVersion: 2010-09-09
Description: | 
  Deploys IAM IdP for Github actions. 
  After deploying, attach IAM permissions to the 'Role' resource created by this template with the permissions you want the Github Action to be able to assume.


Parameters:
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive) (Required)
    Type: String
  RepositoryName:
    Description: Name of GitHub repository (case sensitive) (Required)
    Type: String
  OIDCProviderArn:
    Description: Arn for an existing GitHub OIDC Provider. (Optional. Specify if there is already an IAM IdP created.)
    Default: ""
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials. (Required)
    Default: sts.amazonaws.com
    Type: String


Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""


Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If 
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
  
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff

Outputs:
  Role:
    Value: !GetAtt Role.Arn