version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.local_start_api.parameters]
force_image_build = true



[mysql.deploy.parameters]
stack_name = "mysql-ephemeral-ecr-build"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ephemeral/"
region = "us-east-1"
capabilities = ["CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "pAppName=mysql-ephemeral",
    "pRepoOwner=MadisonReed",
    "pRepoName=mr",
    "pCodestarConnectionArn=arn:aws:codestar-connections:us-east-1:174743933558:connection/d27c0b2b-88c2-45ac-b8f4-89b0e04af6fd",
    "pTriggerBranch=c303/ephemeral/mysql",
    "pCodeBuildComputeType=BUILD_GENERAL1_XLARGE",
    "pDumpBucketName=db-prod-sanitized-backup",
    "pBuildSpecPath=ephemeralenv/database/mysql/buildspec.yml",
    "pEnableDailyTrigger=DISABLED"

]
confirm_changeset = true



[mongo.deploy.parameters]
stack_name = "mongo-ephemeral-ecr-build"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ephemeral/"
region = "us-east-1"
capabilities = ["CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "pAppName=mongo-ephemeral",
    "pRepoOwner=MadisonReed",
    "pRepoName=mr",
    "pCodestarConnectionArn=arn:aws:codestar-connections:us-east-1:174743933558:connection/d27c0b2b-88c2-45ac-b8f4-89b0e04af6fd",
    "pTriggerBranch=c303/ephemeral/mongo",
    "pCodeBuildComputeType=BUILD_GENERAL1_LARGE",
    "pDumpBucketName=mr-mongo-atlas-sanitized-backup",
    "pCodeBuildImage=aws/codebuild/standard:7.0",
    "pBuildSpecPath=ephemeralenv/database/mongo/buildspec.yml",
    "pEnableDailyTrigger=ENABLED"

]
confirm_changeset = true