version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.local_start_api.parameters]
force_image_build = true



[ephemeral.deploy.parameters]
stack_name = "ecs-fargate"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ephemeral/"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM", CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "pVpcId=vpc-094590ab31d2c639f",
    "pPrivateSubnetIds=subnet-050fa317f4ea060dd,subnet-08c6fecb378269d0b"
]
confirm_changeset = true


[ecr.deploy.parameters]
stack_name = "ecr-repos"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ephemeral/ecr/"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "pAppName=pr1"
]
confirm_changeset = true


[pipeline.deploy.parameters]
stack_name = "pipeline"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ephemeral/pipeline/"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "pAppName=pr1"
]
confirm_changeset = true