AWSTemplateFormatVersion: '2010-09-09'
Description: Aurora Serverless MySQL 5.7 cluster from snapshot

Parameters:
  pAppName:
    Type: String
    Default: pr1
    Description: Name to give the application

  pVpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the Virtual Private Network (VPC)

  pVpcCidr:
    Type: String
    Default: 10.20.0.0/16
    Description: CIDR of the VPC

  pRDSSecretName:
    Type: String
    Default: rds!db-9a890b61-a8d0-4dd2-be50-2821f8752698
    Description: Secret associated with primary RDS DB instance

Resources:


  # RDS Aurora SG
  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for MYSQL/Aurora
      VpcId: !Ref pVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref pVpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${pAppName}EphemeralAuroraMySQL

  # Reference: https://github.com/widdix/aws-cf-templates/blob/master/state/rds-aurora-serverless.yaml
  MyAuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: ephemeral
      Engine: aurora-mysql
      EngineVersion: '5.7.mysql_aurora.2.08.3' #'5.7'
      EngineMode: serverless
      DBClusterIdentifier: ephemeral-aurora-mysql-serverless
      # SnapshotIdentifier: your-db-snapshot-identifier # Can't use with master use and password specified...

      # TODO: need to specify secret from external stack. The secret currently used here is referencing one managed by an already existing RDS DB.
      MasterUsername: !Sub '{{resolve:secretsmanager:arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds!db-9a890b61-a8d0-4dd2-be50-2821f8752698-rb2djF:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds!db-9a890b61-a8d0-4dd2-be50-2821f8752698-rb2djF:SecretString:password}}'
      DBSubnetGroupName: madisonreed-development-rds-mysql
      VpcSecurityGroupIds:
        - !GetAtt AuroraSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: Ephemeral Aurora MySQL Serverless
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 2
        MaxCapacity: 16
        SecondsUntilAutoPause: 300

Outputs:
  ClusterEndpoint:
    Description: The endpoint address of the Aurora cluster
    Value: !GetAtt MyAuroraCluster.Endpoint.Address