AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
    Default: pr1
    Description: Application Name
 
Resources:

  ecrWebsiteRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub website-${pAppName}