[prod.deploy.parameters]
stack_name = "lambda-dry-microservice"
resolve_s3 = true
s3_prefix = "lambda-dry-microservice"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "pVpcId=vpc-0c8bfffb4dfe4786a",
    "pPrivateSubnetId1=subnet-03c1e03930be30bd9",
    "pPrivateSubnetId2=subnet-0287a6fb3bf90155f"
]
image_repositories = []