version: 0.2
env:
  git-credential-helper: yes
  exported-variables:
    - IMAGE_TAG

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - apt-get update
      - apt-get install -y qemu-user-static
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker images...
      - | 
        docker buildx build \
          --platform linux/arm64,linux/amd64 \
          -t "$REPOSITORY_URI:latest" \
          -t "$REPOSITORY_URI:$IMAGE_TAG" \
          -f "<dockerfile-path>" . \
          --push \
          --allow incomplete

  post_build:
    commands:
      - echo Build completed on $(date)
      - echo Writing image definition file...
      # Change 'website' to the container name given in the ECS Service's task definition
      - printf '[{"name":"website","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json