FROM mysql:5.7 as builder

# Set the MySQL databases to be created
ARG MYSQL_DATABASES="inventory magento tophat"
ENV MYSQL_DATABASES=${MYSQL_DATABASES}


# needed for initialization
ENV MYSQL_ROOT_PASSWORD=root


# docker-entrypoint.sh does DB init, but also runs the mysql daemon. We only want to run initialization, otherwise the build process will be running forever.
# To resolve this, we replace the `exec "$@"` line at the end of the `docker-entrypoint.sh` script with a simple echo command.
RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]


# Make sure the DB creation script is ran on initialization
# This is used just in case the databases aren't created from the SQL dump file.
COPY create_dbs.sh /docker-entrypoint-initdb.d/create_dbs.sh

# Grant permissions for the script to be executable
RUN chmod +x /docker-entrypoint-initdb.d/create_dbs.sh

# Copy MYSQL dump. This will be initialized during build
COPY dump.sql /docker-entrypoint-initdb.d/


# Need to change the datadir to something else other than /var/lib/mysql because the parent dockerfile defines it as a volume.
RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]



FROM mysql:5.7

COPY --from=builder /initialized-db /var/lib/mysql
