version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.local_start_api.parameters]
force_image_build = true



[ephemeral.deploy.parameters]
stack_name = "rest-api"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ephemeral/color-advisor/"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true